defaults : &defaults
  host: localhost
  adapter: postgres
  user: martian
  db: mrtbbs
  # password: drowssap
  model_files_path: ./src/models
  migration_files_path: ./src/migrations

development:
  <<: *defaults
  db: mrtbbs_development

test:
  <<: *defaults
  db: mrtbbs_test
